FROM nixos/nix:2.31.1-amd64

RUN set -eux; \
    { \
        echo "filter-syscalls = false"; \
        echo "max-jobs = auto"; \
        echo "cores = 0"; \
        echo "build-cores = 0"; \
    } >> /etc/nix/nix.conf

RUN nix-env -f '<nixpkgs>' -iA \
    gnused \
    openssh \
 && nix-store --gc

RUN set -eux; \
    mkdir -p /etc/ssh /var/empty /run /var/log /root/.ssh && \
    touch /var/log/lastlog && \
    echo "sshd:x:498:65534::/var/empty:/run/current-system/sw/bin/nologin" >> /etc/passwd; \
    cp /root/.nix-profile/etc/ssh/sshd_config /etc/ssh/sshd_config && \
    sed -i 's/root:!:/root:*:/' /etc/shadow; \
    sed -i '/^PermitRootLogin/d' /etc/ssh/sshd_config && echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config; \
    ssh-keygen -f /etc/ssh/ssh_host_rsa_key -N "" -t rsa && \
    ssh-keygen -f /etc/ssh/ssh_host_ed25519_key -N "" -t ed25519 && \
    echo "source /root/.nix-profile/etc/profile.d/nix.sh" >> /etc/bashrc && \
    echo "source /etc/bashrc" >> /etc/profile

COPY entrypoint.sh /
RUN chmod 755 /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]